version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: Hello
          command: echo hello
workflows:
  default:
    jobs:
      - build-and-test
